/**
 * Pure helpers for the `npm run scan:portfolio` script.
 *
 * No I/O here. The .ts script (`scripts/scan-portfolio-candidates.ts`)
 * fetches from GitHub and calls these functions to build the
 * candidate report and the decisions JSON.
 *
 * Design constraints (see `.ralph/private-portfolio-candidates.md`):
 *   - The script never pushes to GitHub. Only writes locally.
 *   - Schema is loose (`.passthrough()`); we don't fail closed on
 *     unknown fields, only on `include`.
 *   - tier defaults to `normal` (PORTFOLIO_DEFAULT_TIER) when the
 *     manifest omits it.
 */

import matter from "gray-matter";
import {
	PORTFOLIO_DEFAULT_TIER,
	PortfolioFrontmatterSchema,
	type ResolvedPortfolioFrontmatter,
} from "@/data/portfolio-schema";

/** Repo metadata fetched from GitHub. Used both as scan input and report context. */
export interface RepoInfo {
	owner: string;
	name: string;
	/** GitHub visibility at scan time. */
	visibility: "public" | "private";
	defaultBranch: string;
	description: string | null;
	primaryLanguage: string | null;
	stars: number;
	topics: string[];
}

/** Outcome of parsing one `portfolio.md` blob. */
export interface ManifestParseResult {
	ok: boolean;
	/** Resolved frontmatter (with tier defaulted) on success. */
	data?: ResolvedPortfolioFrontmatter;
	/** Markdown body (the 'blogpost' content) on success. */
	body?: string;
	/** Human-readable error message on failure. */
	error?: string;
}

/**
 * Parse a raw `portfolio.md` text into frontmatter + body.
 *
 * Failure modes (returns `{ ok: false, error }` rather than throwing):
 *   - gray-matter throws on malformed frontmatter delimiters
 *   - Zod fails on missing/non-boolean `include`, invalid primary/tier
 *
 * The body is intentionally preserved on success so the caller can
 * cache it (Phase B's body-cache step writes it to
 * `portfolio-bodies/<owner>-<name>.md`).
 */
export function parsePortfolioManifest(raw: string): ManifestParseResult {
	let parsed: matter.GrayMatterFile<string>;
	try {
		parsed = matter(raw);
	} catch (err) {
		return {
			ok: false,
			error: err instanceof Error ? err.message : String(err),
		};
	}

	const result = PortfolioFrontmatterSchema.safeParse(parsed.data);
	if (!result.success) {
		return {
			ok: false,
			error: result.error.issues
				.map((i) => `${i.path.join(".") || "(root)"}: ${i.message}`)
				.join("; "),
		};
	}

	// Resolve the tier default at consumption time, NOT in the schema,
	// so downstream consumers never see `tier: undefined`.
	const data: ResolvedPortfolioFrontmatter = {
		...result.data,
		tier: result.data.tier ?? PORTFOLIO_DEFAULT_TIER,
	};
	return { ok: true, data, body: parsed.content };
}

/** State of one repo in the candidate report. */
export type ManifestState = "no-manifest" | "included" | "excluded" | "invalid";

/** One row of the candidate report. */
export interface CandidateRow {
	repo: RepoInfo;
	manifestState: ManifestState;
	manifestError?: string;
	frontmatter?: ResolvedPortfolioFrontmatter;
}

/**
 * Build the markdown report content (`portfolio-candidates.md`).
 *
 * Sort: private repos first (they're the focus of this feature),
 * then by repo name. Each row carries visibility, manifest state,
 * resolved tier, summary excerpt, and tag list (preferring manifest
 * tags, falling back to GitHub topics).
 *
 * `escapePipe()` keeps `|` from breaking the table.
 */
export function buildCandidateReport(rows: CandidateRow[], ownerLabel: string): string {
	const sorted = [...rows].sort((a, b) => {
		if (a.repo.visibility !== b.repo.visibility) {
			return a.repo.visibility === "private" ? -1 : 1;
		}
		return a.repo.name.localeCompare(b.repo.name);
	});

	const escapePipe = (s: string) => s.replace(/\|/g, "\\|").replace(/\n+/g, " ");

	const lines: string[] = [
		"# Portfolio candidates",
		"",
		`_Generated by \`npm run scan:portfolio\`. ${sorted.length} repos for owner \`${ownerLabel}\`._`,
		"",
		"| Repo | Visibility | Include | Tier | Summary | Tags |",
		"|---|---|---|---|---|---|",
	];

	for (const row of sorted) {
		const repoCell = `\`${row.repo.owner}/${row.repo.name}\``;
		const visCell = row.repo.visibility === "private" ? "🔒 private" : "🌐 public";
		const includeCell =
			row.manifestState === "included"
				? "✓"
				: row.manifestState === "excluded"
					? "✗"
					: row.manifestState === "invalid"
						? `⚠ invalid`
						: "_no manifest_";
		const tierCell = row.frontmatter?.tier ?? "—";
		const summaryCell = escapePipe((row.frontmatter?.summary ?? "").slice(0, 80));
		const tagsCell = escapePipe(
			(row.frontmatter?.tags ?? row.repo.topics ?? []).slice(0, 5).join(", "),
		);
		lines.push(
			`| ${repoCell} | ${visCell} | ${includeCell} | ${tierCell} | ${summaryCell} | ${tagsCell} |`,
		);
	}

	lines.push("");
	lines.push("## Counts");
	lines.push("");
	const counts = countByState(sorted);
	lines.push(`- Included: ${counts.included}`);
	lines.push(`- Excluded: ${counts.excluded}`);
	lines.push(`- No manifest: ${counts["no-manifest"]}`);
	lines.push(`- Invalid: ${counts.invalid}`);
	lines.push("");
	lines.push("## How to opt in / opt out");
	lines.push("");
	lines.push(
		"Edit `portfolio-decisions.json` to set `include: true|false` per repo. Decisions win over the in-repo manifest.",
	);
	lines.push("");
	lines.push(
		"For private repos without a manifest, seed one with `include: true` to opt in (see Phase B staging step).",
	);
	lines.push("");
	return lines.join("\n");
}

function countByState(rows: CandidateRow[]): Record<ManifestState, number> {
	const counts: Record<ManifestState, number> = {
		included: 0,
		excluded: 0,
		"no-manifest": 0,
		invalid: 0,
	};
	for (const r of rows) counts[r.manifestState]++;
	return counts;
}

/**
 * Initial shape of `portfolio-decisions.json`. Empty object on first
 * run; the user fills it in with per-repo overrides. Decisions JSON
 * wins over the in-repo manifest at consumption time.
 *
 * Example after user edits:
 * ```json
 * {
 *   "marceloprates/some-private-repo": { "include": true }
 * }
 * ```
 */
export type PortfolioDecisions = Record<
	string,
	{
		include?: boolean;
		override?: {
			summary?: string;
			tags?: string[];
			cover?: string;
			slug?: string;
			primary?: ResolvedPortfolioFrontmatter["primary"];
			tier?: ResolvedPortfolioFrontmatter["tier"];
		};
	}
>;

/** Initial empty decisions JSON for first-run. */
export function emptyPortfolioDecisions(): PortfolioDecisions {
	return {};
}
