/**
 * Pure helpers for the `npm run scan:portfolio` script.
 *
 * No I/O here. The .ts script (`scripts/scan-portfolio-candidates.ts`)
 * fetches from GitHub and calls these functions to build the
 * candidate report and the decisions JSON.
 *
 * Design constraints (see `.ralph/private-portfolio-candidates.md`):
 *   - The script never pushes to GitHub. Only writes locally.
 *   - Schema is loose (`.passthrough()`); we don't fail closed on
 *     unknown fields, only on `include`.
 *   - tier defaults to `normal` (PORTFOLIO_DEFAULT_TIER) when the
 *     manifest omits it.
 */

import fs from "node:fs";
import path from "node:path";

import matter from "gray-matter";
import {
	PORTFOLIO_DEFAULT_TIER,
	PortfolioFrontmatterSchema,
	type ResolvedPortfolioFrontmatter,
} from "@/data/portfolio-schema";

/** Repo metadata fetched from GitHub. Used both as scan input and report context. */
export interface RepoInfo {
	owner: string;
	name: string;
	/** GitHub visibility at scan time. */
	visibility: "public" | "private";
	defaultBranch: string;
	description: string | null;
	primaryLanguage: string | null;
	stars: number;
	topics: string[];
}

/** Outcome of parsing one `portfolio.md` blob. */
export interface ManifestParseResult {
	ok: boolean;
	/** Resolved frontmatter (with tier defaulted) on success. */
	data?: ResolvedPortfolioFrontmatter;
	/** Markdown body (the 'blogpost' content) on success. */
	body?: string;
	/** Human-readable error message on failure. */
	error?: string;
}

/**
 * Parse a raw `portfolio.md` text into frontmatter + body.
 *
 * Failure modes (returns `{ ok: false, error }` rather than throwing):
 *   - gray-matter throws on malformed frontmatter delimiters
 *   - Zod fails on missing/non-boolean `include`, invalid primary/tier
 *
 * The body is intentionally preserved on success so the caller can
 * cache it (Phase B's body-cache step writes it to
 * `portfolio-bodies/<owner>-<name>.md`).
 */
export function parsePortfolioManifest(raw: string): ManifestParseResult {
	let parsed: matter.GrayMatterFile<string>;
	try {
		parsed = matter(raw);
	} catch (err) {
		return {
			ok: false,
			error: err instanceof Error ? err.message : String(err),
		};
	}

	const result = PortfolioFrontmatterSchema.safeParse(parsed.data);
	if (!result.success) {
		return {
			ok: false,
			error: result.error.issues
				.map((i) => `${i.path.join(".") || "(root)"}: ${i.message}`)
				.join("; "),
		};
	}

	// Resolve the tier default at consumption time, NOT in the schema,
	// so downstream consumers never see `tier: undefined`.
	const data: ResolvedPortfolioFrontmatter = {
		...result.data,
		tier: result.data.tier ?? PORTFOLIO_DEFAULT_TIER,
	};
	return { ok: true, data, body: parsed.content };
}

/** State of one repo in the candidate report. */
export type ManifestState = "no-manifest" | "included" | "excluded" | "invalid";

/** One row of the candidate report. */
export interface CandidateRow {
	repo: RepoInfo;
	manifestState: ManifestState;
	manifestError?: string;
	frontmatter?: ResolvedPortfolioFrontmatter;
	/**
	 * Raw `portfolio.md` text fetched from raw.githubusercontent.com.
	 * Present only when the file was successfully fetched (even if its
	 * frontmatter failed Zod validation — the body may still be useful).
	 * Absent when the file 404'd.
	 */
	raw?: string;
}

/**
 * Build the markdown report content (`portfolio-candidates.md`).
 *
 * Sort: private repos first (they're the focus of this feature),
 * then by repo name. Each row carries visibility, manifest state,
 * resolved tier, summary excerpt, and tag list (preferring manifest
 * tags, falling back to GitHub topics).
 *
 * `escapePipe()` keeps `|` from breaking the table.
 */
export function buildCandidateReport(rows: CandidateRow[], ownerLabel: string): string {
	const sorted = [...rows].sort((a, b) => {
		if (a.repo.visibility !== b.repo.visibility) {
			return a.repo.visibility === "private" ? -1 : 1;
		}
		return a.repo.name.localeCompare(b.repo.name);
	});

	const escapePipe = (s: string) => s.replace(/\|/g, "\\|").replace(/\n+/g, " ");

	const lines: string[] = [
		"# Portfolio candidates",
		"",
		`_Generated by \`npm run scan:portfolio\`. ${sorted.length} repos for owner \`${ownerLabel}\`._`,
		"",
		"| Repo | Visibility | Include | Tier | Summary | Tags |",
		"|---|---|---|---|---|---|",
	];

	for (const row of sorted) {
		const repoCell = `\`${row.repo.owner}/${row.repo.name}\``;
		const visCell = row.repo.visibility === "private" ? "🔒 private" : "🌐 public";
		const includeCell =
			row.manifestState === "included"
				? "✓"
				: row.manifestState === "excluded"
					? "✗"
					: row.manifestState === "invalid"
						? `⚠ invalid`
						: "_no manifest_";
		const tierCell = row.frontmatter?.tier ?? "—";
		const summaryCell = escapePipe((row.frontmatter?.summary ?? "").slice(0, 80));
		const tagsCell = escapePipe(
			(row.frontmatter?.tags ?? row.repo.topics ?? []).slice(0, 5).join(", "),
		);
		lines.push(
			`| ${repoCell} | ${visCell} | ${includeCell} | ${tierCell} | ${summaryCell} | ${tagsCell} |`,
		);
	}

	lines.push("");
	lines.push("## Counts");
	lines.push("");
	const counts = countByState(sorted);
	lines.push(`- Included: ${counts.included}`);
	lines.push(`- Excluded: ${counts.excluded}`);
	lines.push(`- No manifest: ${counts["no-manifest"]}`);
	lines.push(`- Invalid: ${counts.invalid}`);
	lines.push("");
	lines.push("## How to opt in / opt out");
	lines.push("");
	lines.push(
		"Edit `portfolio-decisions.json` to set `include: true|false` per repo. Decisions win over the in-repo manifest.",
	);
	lines.push("");
	lines.push(
		"For private repos without a manifest, seed one with `include: true` to opt in (see Phase B staging step).",
	);
	lines.push("");
	return lines.join("\n");
}

function countByState(rows: CandidateRow[]): Record<ManifestState, number> {
	const counts: Record<ManifestState, number> = {
		included: 0,
		excluded: 0,
		"no-manifest": 0,
		invalid: 0,
	};
	for (const r of rows) counts[r.manifestState]++;
	return counts;
}

/**
 * Initial shape of `portfolio-decisions.json`. Empty object on first
 * run; the user fills it in with per-repo overrides. Decisions JSON
 * wins over the in-repo manifest at consumption time.
 *
 * Example after user edits:
 * ```json
 * {
 *   "marceloprates/some-private-repo": { "include": true }
 * }
 * ```
 */
export type PortfolioDecisions = Record<
	string,
	{
		include?: boolean;
		override?: {
			summary?: string;
			tags?: string[];
			cover?: string;
			slug?: string;
			primary?: ResolvedPortfolioFrontmatter["primary"];
			tier?: ResolvedPortfolioFrontmatter["tier"];
		};
	}
>;

/** Initial empty decisions JSON for first-run. */
export function emptyPortfolioDecisions(): PortfolioDecisions {
	return {};
}

/* ------------------------------------------------------------------ *
 * Staging — generate seed manifests locally for private repos that
 * don't have one yet. NO REMOTE WRITES — the user copies these to
 * the source repo and commits them per-repo.
 * ------------------------------------------------------------------ */

/**
 * Build the placeholder content for a staged seed manifest.
 *
 * The template matches the locked example in
 * `.ralph/private-portfolio-candidates.md` (Phase B staging section).
 * `summary:` is auto-populated from the repo's description when present
 * so the user sees a useful starting point instead of a blank field.
 *
 * Pure: no I/O. Caller (the scan script) writes the result to disk.
 */
export function buildSeedManifestTemplate(repo: RepoInfo): string {
	const summary = repo.description?.trim() || `Short pitch for ${repo.name}.`;
	const date = new Date().toISOString().slice(0, 10);
	const lines: string[] = [
		"---",
		"include: true",
		`tier: ${PORTFOLIO_DEFAULT_TIER}`,
		"summary: >",
		`  ${summary}`,
		"tags: []",
		"primary: code",
		"---",
		"",
		`# ${repo.name}`,
		"",
		repo.description?.trim() ||
			`Short description or story about ${repo.name}. This body becomes the blogpost section on the portfolio's \`/projects/<slug>\` page.`,
		"",
		"## Background",
		"",
		"Add context here: what problem this solves, why it exists, what's interesting about it.",
		"",
		"<!--",
		`Generated by \`npm run scan:portfolio\` on ${date}.`,
		"Edit `include: false` to opt out, or fill in the placeholder fields above.",
		"After committing this file to the repo, re-run `npm run scan:portfolio` to refresh the candidate report.",
		"-->",
		"",
	];
	return lines.join("\n");
}

/**
 * Folder name for the staged seed of a repo. Uses `<owner>-<name>`
 * because both `/` and `\` are reserved on the filesystem and the
 * scan script may run on Windows too. Repo names can contain `.`,
 * `_`, `-` (all safe) but not `/`.
 */
export function stagingFolderFor(repo: RepoInfo): string {
	return `${repo.owner}-${repo.name}`;
}

/** Outcome of the staging step. */
export interface StagingResult {
	/** Files written (absolute paths). */
	wrote: string[];
	/** Repos that were intentionally NOT staged, with reason. */
	skipped: { repo: string; reason: string }[];
}

/**
 * Write seed `portfolio.md` for every private repo that doesn't have
 * a manifest yet. Public repos are NEVER auto-staged (the user
 * already publishes them — a seed would be noise). Repos that already
 * have a manifest (included/excluded/invalid) are NEVER overwritten
 * in the seed folder (the user owns those decisions).
 *
 * Idempotent: re-running overwrites the seed file with fresh content.
 * The folder layout matches `portfolio-manifests-to-seed/<owner>-<name>/portfolio.md`.
 *
 * NO REMOTE WRITES. This writes only to local disk.
 */
export function stageSeedManifests(
	rows: CandidateRow[],
	outDir: string,
): StagingResult {
	const result: StagingResult = { wrote: [], skipped: [] };

	for (const row of rows) {
		const repoKey = `${row.repo.owner}/${row.repo.name}`;

		if (row.repo.visibility !== "private") {
			result.skipped.push({ repo: repoKey, reason: "public repo (not auto-staged)" });
			continue;
		}

		if (row.manifestState !== "no-manifest") {
			result.skipped.push({
				repo: repoKey,
				reason: `manifest state: ${row.manifestState}`,
			});
			continue;
		}

		const folder = stagingFolderFor(row.repo);
		const dir = path.join(outDir, folder);
		fs.mkdirSync(dir, { recursive: true });
		const filePath = path.join(dir, "portfolio.md");
		fs.writeFileSync(filePath, buildSeedManifestTemplate(row.repo), "utf8");
		result.wrote.push(filePath);
	}

	return result;
}

/* ------------------------------------------------------------------ *
 * Body cache — write raw `portfolio.md` for every opted-in repo to
 * `portfolio-bodies/<owner>-<name>.md` (gitignored) so the build
 * doesn't depend on GitHub being reachable.
 * ------------------------------------------------------------------ */

/** Outcome of the body-cache step. */
export interface BodyCacheResult {
	/** Files written (absolute paths). */
	wrote: string[];
	/** Repos that were intentionally NOT cached, with reason. */
	skipped: { repo: string; reason: string }[];
}

/**
 * Effective opt-in for a single repo, given manifest state + decisions.
 * Decisions JSON wins over the in-repo manifest when both exist.
 */
export function isOptedIn(
	repo: RepoInfo,
	manifestState: ManifestState,
	decisions: PortfolioDecisions,
): boolean {
	const repoKey = `${repo.owner}/${repo.name}`;
	const decision = decisions[repoKey];
	if (decision?.include !== undefined) {
		return decision.include === true;
	}
	return manifestState === "included";
}

/**
 * Cache the raw `portfolio.md` text locally for every opted-in repo.
 *
 * Rules:
 *   - Opted-in via manifest (`include: true`) OR decisions override → cache.
 *   - Opted-out via either → skip.
 *   - Opted-in but no manifest body (404) → skip with explicit reason.
 *   - Invalid manifest + opted-in via decisions → cache the raw anyway;
 *     the user is forcing inclusion, the body is still useful even if
 *     frontmatter needs fixing.
 *
 * NO REMOTE WRITES. The cached file is the exact raw text we fetched
 * (frontmatter + body), preserved byte-for-byte so re-parsing during
 * the build yields the same result.
 *
 * Idempotent: re-running overwrites with fresh content.
 */
export function cacheIncludedBodies(
	rows: CandidateRow[],
	decisions: PortfolioDecisions,
	outDir: string,
): BodyCacheResult {
	const result: BodyCacheResult = { wrote: [], skipped: [] };

	for (const row of rows) {
		const repoKey = `${row.repo.owner}/${row.repo.name}`;
		const repoId: RepoInfo = row.repo;

		if (!isOptedIn(repoId, row.manifestState, decisions)) {
			result.skipped.push({
				repo: repoKey,
				reason: `not opted in (manifest=${row.manifestState})`,
			});
			continue;
		}

		if (row.raw === undefined || row.raw === null) {
			result.skipped.push({
				repo: repoKey,
				reason: "opted in but no manifest body (404 on portfolio.md)",
			});
			continue;
		}

		const dir = path.join(outDir, `${row.repo.owner}-${row.repo.name}`);
		fs.mkdirSync(dir, { recursive: true });
		const filePath = path.join(dir, "portfolio.md");
		fs.writeFileSync(filePath, row.raw, "utf8");
		// Also write a small sidecar with build-time metadata the body
		// fallback (src/lib/content.ts getProjectBySlug) needs:
		// repo visibility for the `private` badge, default tier, and the
		// canonical owner/name. Cheap, gitignored, and avoids a re-fetch
		// from GitHub at build time.
		const sidecarPath = path.join(dir, "portfolio.meta.json");
		const sidecar = {
			owner: row.repo.owner,
			name: row.repo.name,
			visibility: row.repo.visibility,
			defaultBranch: row.repo.defaultBranch,
			stars: row.repo.stars,
		};
		fs.writeFileSync(sidecarPath, JSON.stringify(sidecar, null, 2) + "\n", "utf8");
		result.wrote.push(filePath);
		result.wrote.push(sidecarPath);
	}

	return result;
}

/**
 * Load decisions JSON from disk. Returns `{}` if the file is missing
 * (first run) or invalid (logs warning, treats as empty). Lenient by
 * design — a malformed decisions file shouldn't break the entire scan.
 */
export function loadPortfolioDecisions(filePath: string): PortfolioDecisions {
	if (!fs.existsSync(filePath)) return {};
	try {
		const raw = fs.readFileSync(filePath, "utf8");
		const parsed = JSON.parse(raw);
		if (typeof parsed !== "object" || parsed === null || Array.isArray(parsed)) {
			console.warn(
				`[portfolio] decisions JSON at ${filePath} is not an object; treating as empty`,
			);
			return {};
		}
		return parsed as PortfolioDecisions;
	} catch (err) {
		console.warn(
			`[portfolio] failed to parse decisions JSON at ${filePath}: ${err instanceof Error ? err.message : String(err)}; treating as empty`,
		);
		return {};
	}
}
