import fs from "fs";
import path from "path";
import type { Publication } from "@/types";

/**
 * Read publications from the build-time JSON file (data/publications.scholar.json)
 * generated by `npm run fetch-scholar`.
 *
 * Normalizes citation counts: prefers `citationsUpdated`, then
 * `googleScholarCitations`, then `citations`. Sorts descending by
 * citation count. Loud-warns on read failure (was previously silent —
 * see P0 #4 from the Phase 0-3 implementation loop).
 *
 * @param opts.max   max publications to return (default 9)
 * @param opts.cwd   directory containing data/publications.scholar.json
 *                   (defaults to process.cwd(); injected for tests)
 */
export async function fetchPublications(
	opts: { max?: number; cwd?: string } = {},
): Promise<Publication[]> {
	const { max = 9, cwd = process.cwd() } = opts;
	const pubsPath = path.join(cwd, "data", "publications.scholar.json");

	let rawPubs: unknown[] = [];
	try {
		const raw = fs.readFileSync(pubsPath, "utf8");
		const data = JSON.parse(raw || "{}");
		rawPubs = Array.isArray(data.publications) ? data.publications : [];
	} catch (err) {
		console.warn(
			`[fetchPublications] failed to read ${pubsPath}: ${
				err instanceof Error ? err.message : String(err)
			}. Run 'npm run fetch-scholar' to populate.`,
		);
		return [];
	}

	const normalized: Publication[] = rawPubs.map((p: unknown) => {
		const obj =
			typeof p === "object" && p !== null ? (p as Record<string, unknown>) : {};
		const gs = typeof obj.googleScholarCitations === "number" ? obj.googleScholarCitations : null;
		const updated =
			typeof obj.citationsUpdated === "number"
				? obj.citationsUpdated
				: (gs ?? (typeof obj.citations === "number" ? obj.citations : 0));

		return {
			title: typeof obj.title === "string" ? obj.title : String(obj.title ?? ""),
			venue: typeof obj.venue === "string" ? obj.venue : String(obj.venue ?? ""),
			year: typeof obj.year === "number" ? obj.year : Number(obj.year) || 0,
			url: typeof obj.url === "string" ? obj.url : String(obj.url ?? ""),
			pdfUrl: typeof obj.pdfUrl === "string" ? obj.pdfUrl : undefined,
			citations: updated,
		} as Publication;
	});

	const pubs = normalized.sort((a, b) => (b.citations || 0) - (a.citations || 0));
	return pubs.slice(0, max);
}