import type { Project } from "@/types";
import type { ProjectFrontmatter } from "@/data/project-schema";

/**
 * Resolves a list of selectedProjects entries (strings) into Project
 * objects ready to render. Extracted from the inline JSX in
 * src/app/page.tsx (was a 50+ line IIFE).
 *
 * Three lookup strategies, tried in order per entry:
 *   1. "owner/repo" → match against enriched GitHub projects
 *   2. "/projects/slug" or "slug" → match against content projects
 *   3. raw title → match against enriched GitHub projects by title
 *
 * The content lookup function is injected (default: getProjectBySlug
 * from src/lib/content.ts) so this module is testable without disk I/O.
 */

export interface ContentProjectMeta {
	slug: string;
}

export interface ContentProjectSource {
	/**
	 * Project frontmatter as returned by `getProjectBySlug` from
	 * `src/lib/content.ts`. Loose (`.passthrough()`) so ad-hoc fields
	 * like `stars`, `forks`, `autogenerated`, `original_path` are
	 * preserved at runtime. Runtime conformance is enforced by
	 * `npm run validate:frontmatter` (precommit gate).
	 */
	meta: ProjectFrontmatter;
}

export type ContentLookup = (slug: string) => ContentProjectSource | null;

export interface ProjectMetadataEntry {
	hasLocalPage: boolean;
	slug?: string;
}

export interface ResolveSelectedProjectsInput {
	entries: readonly string[];
	allProjects: readonly Project[];
	contentProjects: readonly ContentProjectMeta[];
	projectMetadata: Record<string, ProjectMetadataEntry>;
	getContentBySlug: ContentLookup;
}

/**
 * Resolve a frontmatter image field (image/cover/excerpt's first <img>)
 * to a concrete src URL. Bare filenames are treated as
 * `/images/projects/{slug}/{filename}`.
 */
export function resolveProjectImage(
	meta: ProjectFrontmatter,
	slug: string,
): string | undefined {
	// pick/fromExcerpt accept `unknown` because the .passthrough() schema
	// surfaces ad-hoc fields (image, description) as `unknown` even when
	// they're string at runtime. The typeof checks below narrow safely.
	const pick = (field: unknown): string | undefined => {
		if (typeof field !== "string") return undefined;
		const img = field.trim();
		if (!img) return undefined;
		return img.startsWith("http") || img.startsWith("/")
			? img
			: `/images/projects/${slug}/${img}`;
	};

	const fromExcerpt = (excerpt: unknown): string | undefined => {
		if (typeof excerpt !== "string") return undefined;
		const m = excerpt.match(/src=["']([^"']+)["']/i);
		return m ? pick(m[1]) : undefined;
	};

	return (
		pick(meta.image) || pick(meta.cover) || fromExcerpt(meta.excerpt) || undefined
	);
}

/**
 * Strip HTML tags from a description string.
 */
function stripHtml(s: string): string {
	return s.replace(/<[^>]+>/g, "").replace(/\s+/g, " ").trim();
}

/**
 * Build a Project from a content project's frontmatter.
 */
function projectFromContent(
	contentMatch: ContentProjectMeta,
	content: ContentProjectSource,
): Project {
	const meta = content.meta;
	const imageSrc = resolveProjectImage(meta, contentMatch.slug);
	// `meta.description` is an ad-hoc field (legacy excerpt name) — typed
	// as unknown via .passthrough(); narrow defensively.
	const descSource: string =
		(typeof meta.excerpt === "string" ? meta.excerpt : "") ||
		(typeof meta.description === "string" ? meta.description : "");
	return {
		title: meta.title || contentMatch.slug,
		desc: stripHtml(descSource),
		tags: meta.tags || [],
		link: `/projects/${contentMatch.slug}`,
		repo: meta.repo || undefined,
		image: imageSrc,
	};
}

/**
 * Resolve a single entry. Returns null if no strategy matched.
 */
function resolveEntry(entry: string, input: ResolveSelectedProjectsInput): Project | null {
	const { allProjects, contentProjects, getContentBySlug } = input;

	// Strategy 1: owner/repo → match against enriched projects or fall through to slug
	if (entry.includes("/")) {
		const byRepo = allProjects.find(
			(p) => p.repo === entry || (p.link && p.link.includes(entry.split("/")[1])),
		);
		if (byRepo) return byRepo;

		// Repo not found in enriched list — try the last path segment as a local slug
		const last = entry.split("/").filter(Boolean).pop();
		if (last) {
			const match = contentProjects.find(
				(c) => c.slug.toLowerCase() === last.toLowerCase(),
			);
			if (match) {
				const content = getContentBySlug(match.slug);
				if (content) return projectFromContent(match, content);
			}
		}
	}

	// Strategy 2: /projects/slug or bare slug → content lookup
	let slug = entry;
	if (slug.startsWith("/projects/")) slug = slug.replace("/projects/", "");
	const contentMatch = contentProjects.find(
		(c) => c.slug.toLowerCase() === slug.toLowerCase(),
	);
	if (contentMatch) {
		const content = getContentBySlug(contentMatch.slug);
		if (content) return projectFromContent(contentMatch, content);
	}

	// Strategy 3: title match against enriched projects
	const byTitle = allProjects.find(
		(p) => p.title && p.title.toLowerCase() === entry.toLowerCase(),
	);
	if (byTitle) return byTitle;

	return null;
}

/**
 * Resolve all entries, preserving order. Skips unresolvable entries silently
 * (a missing project just disappears from the section).
 */
export function resolveSelectedProjects(input: ResolveSelectedProjectsInput): Project[] {
	const resolved: Project[] = [];
	for (const entry of input.entries) {
		const r = resolveEntry(entry, input);
		if (r) resolved.push(r);
	}
	return resolved;
}

// Re-export for convenience
export { resolveProjectImage as resolveProjectImageFromMeta };