import { describe, expect, it } from "vitest";
import { ProjectFrontmatterSchema } from "../project-schema";

describe("ProjectFrontmatterSchema", () => {
    const valid = { title: "easyshader" };

    it("accepts a minimal entry with only the required title", () => {
        expect(ProjectFrontmatterSchema.safeParse(valid).success).toBe(true);
    });

    it("accepts a complete entry with cover, tags, excerpt, repo", () => {
        const complete = {
            title: "easyshader",
            cover: "/images/projects/easyshader/print-2.png",
            excerpt: "A Python DSL for 3D art using SDFs.",
            tags: ["Python", "SDF", "Raymarching"],
            repo: "marceloprates/easyshader",
            stars: 25,
            forks: 2,
            autogenerated: false,
            original_path: "/projects/easyshader",
        };
        expect(ProjectFrontmatterSchema.safeParse(complete).success).toBe(true);
    });

    it("accepts an external URL cover (raw.githubusercontent, imgur, etc.)", () => {
        const external = {
            title: "TSP-Animation",
            cover: "https://raw.githubusercontent.com/marceloprates/TSP-Animation/main/videos/animation4-nov5-small.gif",
        };
        expect(ProjectFrontmatterSchema.safeParse(external).success).toBe(true);
    });

    it("accepts an empty-string cover as absent (fallback to excerpt-img)", () => {
        // Empty string is intentionally allowed-but-empty rather than
        // rejected: getAllProjects() treats "" the same as undefined and
        // falls back to the excerpt's <img src>.
        expect(ProjectFrontmatterSchema.safeParse({ ...valid, cover: "" }).success).toBe(true);
    });

    it("rejects an empty or missing title", () => {
        expect(ProjectFrontmatterSchema.safeParse({}).success).toBe(false);
        expect(ProjectFrontmatterSchema.safeParse({ title: "" }).success).toBe(false);
    });

    it("preserves unknown frontmatter fields via passthrough", () => {
        const withExtras = {
            ...valid,
            // Real-world frontmatter often has fields the schema doesn't model:
            category: "experiments",
            nested: { deeply: { arbitrary: true } },
            list: [1, 2, "three"],
        };
        const result = ProjectFrontmatterSchema.parse(withExtras);
        expect(result.category).toBe("experiments");
        expect(result.nested).toEqual({ deeply: { arbitrary: true } });
        expect(result.list).toEqual([1, 2, "three"]);
    });
});
