import { describe, expect, it } from "vitest";
import {
    ProjectFrontmatterSchema,
    type ProjectFrontmatter,
    type ProjectMeta,
} from "../project-schema";

describe("ProjectFrontmatterSchema", () => {
    const valid = { title: "easyshader" };

    it("accepts a minimal entry with only the required title", () => {
        expect(ProjectFrontmatterSchema.safeParse(valid).success).toBe(true);
    });

    it("accepts a complete entry with cover, tags, excerpt, repo", () => {
        const complete = {
            title: "easyshader",
            cover: "/images/projects/easyshader/print-2.png",
            excerpt: "A Python DSL for 3D art using SDFs.",
            tags: ["Python", "SDF", "Raymarching"],
            repo: "marceloprates/easyshader",
            stars: 25,
            forks: 2,
            autogenerated: false,
            original_path: "/projects/easyshader",
        };
        expect(ProjectFrontmatterSchema.safeParse(complete).success).toBe(true);
    });

    it("accepts an external URL cover (raw.githubusercontent, imgur, etc.)", () => {
        const external = {
            title: "TSP-Animation",
            cover: "https://raw.githubusercontent.com/marceloprates/TSP-Animation/main/videos/animation4-nov5-small.gif",
        };
        expect(ProjectFrontmatterSchema.safeParse(external).success).toBe(true);
    });

    it("accepts an empty-string cover as absent (fallback to excerpt-img)", () => {
        // Empty string is intentionally allowed-but-empty rather than
        // rejected: getAllProjects() treats "" the same as undefined and
        // falls back to the excerpt's <img src>.
        expect(ProjectFrontmatterSchema.safeParse({ ...valid, cover: "" }).success).toBe(true);
    });

    it("rejects an empty or missing title", () => {
        expect(ProjectFrontmatterSchema.safeParse({}).success).toBe(false);
        expect(ProjectFrontmatterSchema.safeParse({ title: "" }).success).toBe(false);
    });

    it("preserves unknown frontmatter fields via passthrough", () => {
        const withExtras = {
            ...valid,
            // Real-world frontmatter often has fields the schema doesn't model:
            category: "experiments",
            nested: { deeply: { arbitrary: true } },
            list: [1, 2, "three"],
        };
        const result = ProjectFrontmatterSchema.parse(withExtras);
        expect(result.category).toBe("experiments");
        expect(result.nested).toEqual({ deeply: { arbitrary: true } });
        expect(result.list).toEqual([1, 2, "three"]);
    });
});

describe("ProjectMeta (build-time type)", () => {
    // ProjectMeta is purely a type — runtime assertions must go through the
    // schema. These tests verify the type SHAPE via compile-time helpers
    // (TypeScript checks) AND that ProjectFrontmatterSchema accepts what
    // ProjectMeta would carry at runtime.

    it("ProjectMeta requires title + slug and optionally carries image + repo", () => {
        // Compile-time type assertion. If ProjectMeta's shape ever drifts
        // (e.g. slug becomes optional), this fails to typecheck.
        const minimal: ProjectMeta = {
            title: "minimal",
            slug: "minimal",
        };
        expect(minimal.slug).toBe("minimal");
        expect(minimal.image).toBeUndefined();

        const withEverything: ProjectMeta = {
            title: "easyshader",
            slug: "easyshader",
            image: "/images/projects/easyshader/print-2.png",
            cover: "/images/projects/easyshader/print-2.png",
            repo: "marceloprates/easyshader",
            excerpt: "A Python DSL for 3D art using SDFs.",
            tags: ["Python", "SDF"],
            date: "2024-01-01",
        };
        expect(withEverything.image).toBe("/images/projects/easyshader/print-2.png");
        expect(withEverything.repo).toBe("marceloprates/easyshader");
    });

    it("ProjectMeta preserves all ProjectFrontmatter fields plus slug + image", () => {
        // Round-trip: ProjectMeta-shaped object should pass ProjectFrontmatterSchema.parse
        // (image is a build-time field, not a schema field, but the rest is).
        const full: ProjectMeta = {
            title: "full",
            slug: "full",
            image: "https://example.com/cover.png",
            cover: "https://example.com/cover.png",
            excerpt: "Excerpt text",
            date: "2024-01-01",
            tags: ["t1", "t2"],
            repo: "owner/repo",
            // Ad-hoc fields preserved via .passthrough():
            stars: 100,
            forks: 5,
            autogenerated: false,
            original_path: "/projects/full",
        };
        const parsed = ProjectFrontmatterSchema.parse(full);
        expect(parsed.title).toBe("full");
        expect(parsed.repo).toBe("owner/repo");
        expect(parsed.tags).toEqual(["t1", "t2"]);
        // Ad-hoc fields survive .passthrough():
        const extras = parsed as ProjectFrontmatter & {
            stars?: number;
            forks?: number;
            autogenerated?: boolean;
        };
        expect(extras.stars).toBe(100);
        expect(extras.forks).toBe(5);
        expect(extras.autogenerated).toBe(false);
    });

    it("ProjectMeta slug is non-optional (required by getAllProjects contract)", () => {
        // Type assertion: a ProjectMeta with missing slug fails typecheck.
        // The runtime check is via TypeScript only.
        const meta: ProjectMeta = { title: "t", slug: "s" };
        const slug: string = meta.slug;
        expect(slug).toBe("s");
    });
});
