import { ArrowRight } from "lucide-react";
import { ResumeTabs } from "@/components/resume/ResumeTabs";
import { githubConfig } from "../../config/github";

import { AboutSection } from "@/components/AboutSection";
import { ProjectCard } from "@/components/ProjectCard";
import { TileButton } from "@/components/TileButton";
import { projects as rawProjects } from "@/data/projects";
import { selectedProjects } from "@/data/selected-projects";
import {
	getAllProjects as getAllContentProjects,
	getProjectBySlug,
} from "@/lib/content";
import { getProjectMetadata } from "@/lib/project-metadata.server";
import { tiles } from "@/data/tiles";
import { publications as staticPublications } from "@/data/publications";
import type { Publication, Project } from "@/types";
import { Section } from "@/components/Section";
import { PublicationCard } from "@/components/PublicationCard";
import { StarshipCard } from "@/components/StarshipCard";
import { enrichProjects } from "@/lib/project-enricher";
import fs from "fs";
import path from "path";
import ThemeToggle from "@/components/ThemeToggle";
import FilmGrain from "@/components/FilmGrain";

export default async function Home() {
	// Compute age on the server for simple static content
	const birthDate = new Date(1992, 8, 9); // 1992-09-09 (month is 0-based)
	const today = new Date();
	let years = today.getFullYear() - birthDate.getFullYear();
	const monthDiff = today.getMonth() - birthDate.getMonth();
	if (
		monthDiff < 0 ||
		(monthDiff === 0 && today.getDate() < birthDate.getDate())
	) {
		years--;
	}

	// Read publications from the local JSON file generated by fetch-scholar.js
	const fetchPublications = async (max = 9): Promise<Publication[]> => {
		try {
			// Read publications from disk at build time
			const pubsPath = path.join(
				process.cwd(),
				"data",
				"publications.scholar.json",
			);
			const raw = fs.readFileSync(pubsPath, "utf8");
			const data = JSON.parse(raw || "{}");

			// Sort by citation count (highest first) and respect `max` limit
			const rawPubs: unknown[] = Array.isArray(data.publications)
				? data.publications
				: [];

			// Normalize citation counts: prefer citationsUpdated (set by fetch-scholar.js),
			// then googleScholarCitations, then the original semantic scholar `citations`.
			const normalized: Publication[] = rawPubs.map((p: unknown) => {
				const obj =
					typeof p === "object" && p !== null
						? (p as Record<string, unknown>)
						: {};
				const gs =
					typeof obj.googleScholarCitations === "number"
						? obj.googleScholarCitations
						: null;
				const updated =
					typeof obj.citationsUpdated === "number"
						? obj.citationsUpdated
						: (gs ?? (typeof obj.citations === "number" ? obj.citations : 0));

				// Build a safe Publication object, coercing or defaulting fields when necessary.
				return {
					title:
						typeof obj.title === "string" ? obj.title : String(obj.title ?? ""),
					venue:
						typeof obj.venue === "string" ? obj.venue : String(obj.venue ?? ""),
					year: typeof obj.year === "number" ? obj.year : Number(obj.year) || 0,
					url: typeof obj.url === "string" ? obj.url : String(obj.url ?? ""),
					pdfUrl: typeof obj.pdfUrl === "string" ? obj.pdfUrl : undefined,
					citations: updated,
				} as Publication;
			});

			const pubs: Publication[] = normalized.sort(
				(a: Publication, b: Publication) =>
					(b.citations || 0) - (a.citations || 0),
			);

			return pubs.slice(0, max);
		} catch {
			return [];
		}
	};

	let publications: Publication[] = [];
	try {
		publications = await fetchPublications();
	} catch {
		publications = [];
	}

	const publicationsToShow = publications.length
		? publications
		: staticPublications;

	// Enrich projects with GitHub stats; writes github-projects.json as a side effect.
	const { enriched: projects } = await enrichProjects(rawProjects);

	// Resolve local page links for projects that have content pages
	const projectMetadata = getProjectMetadata();
	const projectsFinal: Project[] = projects.map((p) => {
		try {
			if (p.repo && projectMetadata[p.repo]?.hasLocalPage) {
				const slug = projectMetadata[p.repo].slug || p.repo.split("/")[1];
				return { ...p, link: `/projects/${slug}` } as Project;
			}
		} catch {
			// ignore and fallback to original link
		}
		return p;
	});

	return (
		<div className="min-h-screen transition-colors">
			{/* Subtle film grain overlay (client component) */}
			<FilmGrain
				className="pointer-events-none fixed inset-0"
				intensity={20}
				fps={0}
				tileSize={800}
			/>

			<ThemeToggle />

			<main className="px-4 py-16 mx-auto max-w-7xl">
				{/* Hero */}
				<header className="mb-10 text-center">
					<h1 className="text-4xl font-extrabold leading-tight mb-4 text-gray-900 dark:text-white libre-baskerville">
						{">"} Hi, I&apos;m{" "}
						<span className="relative inline-block">
							<span
								className="bg-yellow-200 dark:bg-yellow-400/60 px-1 rounded-sm z-0 absolute inset-0 -skew-y-2 pointer-events-none"
								aria-hidden="true"
							>
								<span className="absolute inset-0 opacity-60 mix-blend-multiply bg-gradient-to-br from-transparent via-black/5 to-transparent" />
								<span className="absolute inset-0 opacity-90 mix-blend-multiply bg-[length:40px_40px] bg-[url('data:image/svg+xml;utf8,<svg width=\'40\' height=\'40\' xmlns=\'http://www.w3.org/2000/svg\'><filter id=\'grain\'><feTurbulence type=\'fractalNoise\' baseFrequency=\'1.0\' numOctaves=\'3\'/></filter><rect width=\'100%\' height=\'100%\' filter=\'url(%23grain)\' opacity=\'0.35\'/></svg>')]" />
							</span>
							<span className="relative z-10 font-extrabold text-gray-900 dark:text-gray-900">
								Marcelo Prates!
							</span>
						</span>
					</h1>
					<p className="mx-auto max-w-3xl text-lg text-gray-700 dark:text-gray-300 text-justify">
						My name is Marcelo de Oliveira Rosa Prates, I’m a {years}yo software
						developer and artist based in Porto Alegre, Brazil.
					</p>
				</header>

				{/* Quick tiles navigation */}
				<section aria-label="Quick links" className="mb-20">
					<div className="grid grid-cols-2 md:grid-cols-4 auto-rows-[88px] gap-4">
						{tiles.map((tile) => (
							<TileButton key={tile.label} tile={tile} />
						))}
					</div>
				</section>

				{/* About + details */}
				<AboutSection
					name="Marcelo de Oliveira Rosa Prates"
					role="Software developer, data scientist & generative artist"
					location="Porto Alegre, Brazil"
				/>

				{/* Projects */}
				<section id="projects" className="mt-10 mb-24">
					<div className="flex items-center justify-between mb-8">
						<h2 className="text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
							Selected Projects
						</h2>
						<a
							href="#"
							className="text-sm font-medium text-blue-600 dark:text-blue-400 hover:underline inline-flex items-center gap-1"
							aria-label="See all projects"
						>
							All <ArrowRight className="w-4 h-4" />
						</a>
					</div>
					<div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
						<StarshipCard href="/starship" />
						{/* Render exactly the manually selected projects in the configured order. */}
						{(() => {
							// Helper: resolve a frontmatter `image`/`cover` field to a concrete src string.
							const projectImageSrc = (
								meta: Record<string, unknown>,
								slug: string,
							): string | undefined => {
								const pick = (field?: string) => {
									if (!field) return undefined;
									const img = field.trim();
									return img.startsWith("http") || img.startsWith("/")
										? img
										: `/images/projects/${slug}/${img}`;
								};
								const fromExcerpt = (excerpt?: string) => {
									const m =
										typeof excerpt === "string"
											? excerpt.match(/src=["']([^"']+)["']/i)
											: null;
									return m ? pick(m[1]) : undefined;
								};
								return (
									pick(meta.image as string | undefined) ||
									pick(meta.cover as string | undefined) ||
									fromExcerpt(meta.excerpt as string | undefined)
								);
							};
							// Load local content projects to allow references to content pages like '/projects/streamlines' or 'streamlines'
							const contentProjects = getAllContentProjects();

							const selectedResolved: Project[] = [];

							for (const entry of selectedProjects) {
								// If entry looks like an owner/repo (contains '/'), try repo first.
								if (entry.includes("/")) {
									const found = projectsFinal.find(
										(p) =>
											p.repo === entry ||
											(p.link && p.link.includes(entry.split("/")[1])),
									);
									if (found) {
										selectedResolved.push(found);
										continue;
									}

									// Repository not found — try treating the last path segment as a local slug
									const last = entry.split("/").filter(Boolean).pop();
									if (last) {
										const contentMatch = contentProjects.find(
											(c) => c.slug.toLowerCase() === last.toLowerCase(),
										);
										if (contentMatch) {
											const local = getProjectBySlug(contentMatch.slug);
											if (local) {
												const meta = local.meta || {};
												// Resolve an optional image declared in frontmatter. If it's a
												// bare filename, assume it's stored under /images/projects/{slug}/
												let imageSrc: string | undefined;
												// Prefer an explicit `image` frontmatter field
												if (meta.image && typeof meta.image === "string") {
													const img = meta.image.trim();
													if (img.startsWith("http") || img.startsWith("/"))
														imageSrc = img;
													else
														imageSrc = `/images/projects/${contentMatch.slug}/${img}`;
												}
												// Allow using `cover` frontmatter field (common in content) as image
												if (
													!imageSrc &&
													meta.cover &&
													typeof meta.cover === "string"
												) {
													const img = meta.cover.trim();
													if (img.startsWith("http") || img.startsWith("/"))
														imageSrc = img;
													else
														imageSrc = `/images/projects/${contentMatch.slug}/${img}`;
												}
												// Fallback: allow frontmatter `excerpt` to contain an <img src="..."> tag
												if (
													!imageSrc &&
													meta.excerpt &&
													typeof meta.excerpt === "string"
												) {
													const m = meta.excerpt.match(/src=["']([^"']+)["']/i);
													if (m && m[1]) {
														const img = m[1].trim();
														if (img.startsWith("http") || img.startsWith("/"))
															imageSrc = img;
														else
															imageSrc = `/images/projects/${contentMatch.slug}/${img}`;
													}
												}

												selectedResolved.push({
													title: meta.title || contentMatch.slug,
													desc: (meta.excerpt || meta.description || "")
														.replace(/<[^>]+>/g, "")
														.trim(),
													tags: meta.tags || [],
													link: `/projects/${contentMatch.slug}`,
													repo: meta.repo || undefined,
													image: imageSrc,
												});
												continue;
											}
										}
									}
								}

								// If entry looks like a path '/projects/slug', normalize to slug and try content
								let slug = entry;
								if (slug.startsWith("/projects/"))
									slug = slug.replace("/projects/", "");
								const contentMatch = contentProjects.find(
									(c) => c.slug.toLowerCase() === slug.toLowerCase(),
								);
								if (contentMatch) {
									const local = getProjectBySlug(contentMatch.slug);
									if (local) {
										const meta = local.meta || {};
										const imageSrc = projectImageSrc(meta, contentMatch.slug);

										selectedResolved.push({
											title: meta.title || contentMatch.slug,
											desc: (meta.excerpt || meta.description || "")
												.replace(/<[^>]+>/g, "")
												.trim(),
											tags: meta.tags || [],
											link: `/projects/${contentMatch.slug}`,
											repo: meta.repo || undefined,
											image: imageSrc,
										});
										continue;
									}
								}

								// As a last resort, try to match by title in fetched projects
								const byTitle = projectsFinal.find(
									(p) =>
										p.title && p.title.toLowerCase() === entry.toLowerCase(),
								);
								if (byTitle) selectedResolved.push(byTitle);
							}

							return selectedResolved.map((p) => (
								<ProjectCard key={p.title} project={p} />
							));
						})()}
					</div>
				</section>

				{/* Open Source */}
				<section id="open-source" className="mt-6 mb-24">
					<div className="flex items-center justify-between mb-8">
						<h2 className="text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
							Open Source
						</h2>
						<a
							href="https://github.com/marceloprates"
							className="text-sm font-medium text-blue-600 dark:text-blue-400 hover:underline inline-flex items-center gap-1"
							aria-label="See GitHub"
						>
							All on GitHub <ArrowRight className="w-4 h-4" />
						</a>
					</div>
					<div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
						{projectsFinal
							.filter(
								(p) =>
									p.repo && !githubConfig.excludeFromPages.includes(p.repo!),
							)
							.sort((a, b) => (b.stars || 0) - (a.stars || 0))
							.map((p) => (
								<ProjectCard key={p.title} project={p} />
							))}
					</div>
				</section>

				{/* Papers */}
				<Section
					id="papers"
					title="Selected Papers"
					gradient="from-emerald-500 via-teal-500 to-cyan-500"
				>
					<div className="mt-6">
						<div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
							{publicationsToShow.map((pub: Publication) => (
								<PublicationCard key={pub.title} publication={pub} />
							))}
						</div>
					</div>
					<p className="mt-8 text-sm text-gray-600 dark:text-gray-300">
						More on{" "}
						<a
							href="https://www.semanticscholar.org/author/Marcelo-O.-R.-Prates/144677268"
							target="_blank"
							rel="noopener noreferrer"
							className="text-blue-600 dark:text-blue-400 hover:underline"
						>
							Semantic Scholar
						</a>
						.
					</p>
				</Section>

				{/* Resume: tabbed ATS variants */}
				<Section
					id="resume"
					title="Resume"
					gradient="from-pink-500 via-orange-500 to-amber-400"
				>
					<ResumeTabs />
				</Section>
			</main>
		</div>
	);
}
