#!/usr/bin/env -S npx tsx
/**
 * scripts/validate-content-frontmatter.ts
 *
 * Walks content/posts/*.md and content/projects/*.md, parses each
 * frontmatter via gray-matter, and calls .parse() against the matching
 * Zod schema. Prints filename + Zod issue on failure; exits 1.
 *
 * Run on demand:
 *   npm run validate:frontmatter
 *
 * Wired into `npm run precommit` so a malformed frontmatter commit
 * fails the local gate before it reaches CI.
 *
 * NOT auto-invoked in the Next build hot path — calling .parse() on
 * every getAllPosts/getAllProjects iteration would hurt build
 * throughput, and Zod errors there should already be caught by
 * TypeScript (since PostMeta/ProjectMeta derive from the same schemas).
 *
 * Schemas are loose (.passthrough()) so ad-hoc fields like legacyId,
 * stars, autogenerated, original_path are preserved. The script only
 * catches genuinely broken frontmatter (missing required fields,
 * wrong types).
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import matter from "gray-matter";
import type { ZodTypeAny } from "zod";
import { PostFrontmatterSchema } from "../src/data/post-schema";
import { ProjectFrontmatterSchema } from "../src/data/project-schema";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const CONTENT_DIR = path.resolve(__dirname, "..", "content");

type Kind = "post" | "project";

const SCHEMAS: Record<
	Kind,
	{ schema: ZodTypeAny; dir: string; label: string }
> = {
	post: {
		schema: PostFrontmatterSchema,
		dir: path.join(CONTENT_DIR, "posts"),
		label: "post",
	},
	project: {
		schema: ProjectFrontmatterSchema,
		dir: path.join(CONTENT_DIR, "projects"),
		label: "project",
	},
};

interface Failure {
	file: string;
	issues: string[];
}

function validateKind(kind: Kind): { ok: number; failures: Failure[] } {
	const { schema, dir, label } = SCHEMAS[kind];
	if (!fs.existsSync(dir)) {
		console.log(`[${label}s] dir not found: ${dir} (skipped)`);
		return { ok: 0, failures: [] };
	}

	const files = fs
		.readdirSync(dir)
		.filter((f) => f.endsWith(".md") || f.endsWith(".markdown"));

	const failures: Failure[] = [];
	let ok = 0;
	for (const file of files) {
		const fullPath = path.join(dir, file);
		const raw = fs.readFileSync(fullPath, "utf8");
		const parsed = matter(raw);
		const result = schema.safeParse(parsed.data);
		if (result.success) {
			ok++;
			continue;
		}
		failures.push({
			file: path.relative(CONTENT_DIR, fullPath),
			issues: result.error.issues.map(
				(i) => `${i.path.join(".") || "(root)"}: ${i.message}`,
			),
		});
	}
	return { ok, failures };
}

function main(): void {
	let totalOk = 0;
	let totalFailed = 0;
	for (const kind of ["post", "project"] as Kind[]) {
		const { ok, failures } = validateKind(kind);
		totalOk += ok;
		if (failures.length > 0) {
			console.error(
				`\n[${SCHEMAS[kind].label}s] ${failures.length} file(s) failed:`,
			);
			for (const f of failures) {
				console.error(`  ${f.file}`);
				for (const issue of f.issues) {
					console.error(`    - ${issue}`);
				}
			}
			totalFailed += failures.length;
		} else if (ok > 0) {
			console.log(`[${SCHEMAS[kind].label}s] ${ok} file(s) OK`);
		}
	}
	console.log(`\nSummary: ${totalOk} OK, ${totalFailed} failed`);
	process.exit(totalFailed > 0 ? 1 : 0);
}

main();
