import { z } from "zod";

/**
 * Zod schema for project markdown frontmatter under `content/projects/`.
 *
 * Loose (`.passthrough()`) because frontmatter is user-edited and may
 * include ad-hoc fields like `stars`, `forks`, `repo`, `autogenerated`,
 * `original_path`, etc. Schema fails closed only on the required fields;
 * extras are preserved unchanged so build-time readers see them too.
 *
 * **Cover contract**:
 *   - Primary:  `cover: <url-or-path>` (relative `/images/...` or absolute `https://...`)
 *   - Fallback: 1st `<img src="...">` extracted from `excerpt:` at build time
 *     (see `src/lib/content.ts` getAllProjects())
 *
 * Schema is deliberately NOT auto-invoked from the build hot path —
 * calling `.parse()` on every getAllProjects() iteration hurts Next build
 * throughput. Use `ProjectFrontmatterSchema.parse()` from validation scripts
 * or vitest fixtures explicitly when needed.
 *
 * @example valid project frontmatter
 * ```yaml
 * ---
 * title: easyshader
 * tags: [Python, SDF]
 * excerpt: "A Python DSL for 3D art using signed distance functions…"
 * cover: /images/projects/easyshader/print-2.png
 * repo: marceloprates/easyshader
 * stars: 25
 * forks: 2
 * autogenerated: false
 * ---
 * ```
 */
export const ProjectFrontmatterSchema = z
	.object({
		/** Required. Card title + `[slug]/page.tsx` heading. */
		title: z.string().min(1),
		/** Optional. Plain text or HTML string. If HTML, first `<img src>` is the cover fallback. */
		excerpt: z.string().optional(),
		/** Optional. Primary cover field. URL or path. Empty string = use excerpt fallback. */
		cover: z.string().optional(),
		/** Optional ISO date string. Used for sort + display. */
		date: z.string().optional(),
		/** Optional tag list. Strings only. */
		tags: z.array(z.string()).optional(),
		/** Optional GitHub `owner/repo` shorthand. */
		repo: z.string().optional(),
	})
	.passthrough();

export type ProjectFrontmatter = z.infer<typeof ProjectFrontmatterSchema>;
